//! FFI bindings to the OpenTimelineIO C-Bindings library.
//!
//! This crate provides raw Rust bindings generated by `bindgen` from the
//! OpenTimelineIO C-Bindings headers.
//!
//! ## Setup
//!
//! Initialize the git submodule to get the C bindings source:
//! ```sh
//! git submodule add https://github.com/OpenTimelineIO/OpenTimelineIO-C-Bindings vendor/OpenTimelineIO-C-Bindings
//! git submodule update --init --recursive
//! ```
//!
//! The build script will compile the C library and generate Rust bindings automatically.

#[cfg(feature = "otio-native")]
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[cfg(not(feature = "otio-native"))]
pub mod stub {
    //! Stub module when OTIO C bindings are not available.
    //! The main crate uses its own JSON-based OTIO parser as a fallback.
}
